In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('IMDB-Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
# first we change this case into an lowercase
df['review'] = df['review'].str.lower()
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [ ]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [ ]:
# Removing the HTML tags from the text using REGEX
import re
def remove_tags(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'',text)

df['review'] = df['review'].apply(remove_tags)
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [ ]:
# Removing the Punctuations from the Text using the REGEX (!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~)
import string,time
string.punctuation

# slow method
def remove_punc(text):
  for char in string.punctuation:
    text = text.replace(char,'')
  return text

time1 = time.time()
df['review'] = df['review'].apply(remove_punc)
time2 = time.time() - time1
print(time2)

0.7154901027679443

In [ ]:
# fast method
table = str.maketrans('','',string.punctuation)

def remove_punc1(text):
  return text.translate(table)

time3 = time.time()
df['review'] = df['review'].apply(remove_punc1)
time4 = time.time() - time3
print(time4)

0.9933559894561768

In [ ]:
# fastest amoung this 3
# Create a regex pattern: '[!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~]'
punct_pattern = f"[{string.punctuation}]"

# Time the vectorized approach
time_start = time.time()
df['review'] = df['review'].str.replace(punct_pattern, '', regex=True)
time_end = time.time() - time_start

print("Vectorized Regex Time:", time_end)

Vectorized Regex Time: 0.2330467700958252

In [ ]:
# for extra here we learning how to convert the short word into long form :
short_forms = {
    "GN": "Good Night",
    "GM": "Good Morning",
    "GE": "Good Evening",
    "GA": "Good Afternoon",
    "GTG": "Got To Go",
    "BRB": "Be Right Back",
    "BTW": "By The Way",
    "LOL": "Laughing Out Loud",
    "OMG": "Oh My God",
    "IDK": "I Don't Know",
    "IMO": "In My Opinion",
    "IMHO": "In My Humble Opinion",
    "TBH": "To Be Honest",
    "TTYL": "Talk To You Later",
    "ASAP": "As Soon As Possible",
    "FYI": "For Your Information",
    "FAQ": "Frequently Asked Questions",
    "DIY": "Do It Yourself",
    "RIP": "Rest In Peace",
    "VIP": "Very Important Person",
    "AKA": "Also Known As",
    "ETA": "Estimated Time of Arrival",
    "DOB": "Date of Birth",
    "ATM": "Automated Teller Machine",
    "PIN": "Personal Identification Number",
    "OTP": "One Time Password",
    "DM": "Direct Message",
    "PM": "Private Message",
    "IRL": "In Real Life",
    "TMI": "Too Much Information",
    "FOMO": "Fear Of Missing Out",
    "YOLO": "You Only Live Once",
    "WYD": "What You Doing",
    "WBU": "What About You",
    "HBU": "How About You",
    "LMK": "Let Me Know",
    "NVM": "Never Mind",
    "IDC": "I Don't Care",
    "ILY": "I Love You",
    "ILU": "I Love You",
    "XOXO": "Hugs And Kisses",
    "BFF": "Best Friends Forever",
    "BF": "Boyfriend",
    "GF": "Girlfriend",
    "BRO": "Brother",
    "THX": "Thanks",
    "TY": "Thank You",
    "TYSM": "Thank You So Much",
    "NP": "No Problem",
    "YW": "You're Welcome",
    "PLS": "Please",
    "SRY": "Sorry",
    "OFC": "Of Course",
    "BC": "Because",
    "CU": "See You",
    "TC": "Take Care",
    "GNITE": "Good Night",
    "GWS": "Get Well Soon",
    "HBD": "Happy Birthday",
    "HNY": "Happy New Year",
    "MerryX": "Merry Christmas",
    "GL": "Good Luck",
    "HF": "Have Fun",
    "WB": "Welcome Back",
    "WTG": "Way To Go",
    "GG": "Good Game",
    "OP": "Original Poster",
    "AMA": "Ask Me Anything",
    "ICYMI": "In Case You Missed It",
    "TLDR": "Too Long Didn't Read",
    "FTW": "For The Win",
    "WTF": "What The Heck",
    "SMH": "Shaking My Head",
    "JK": "Just Kidding",
    "JIC": "Just In Case",
    "RN": "Right Now",
    "ASL": "Age Sex Location",
    "B4": "Before",
    "L8R": "Later",
    "2DAY": "Today",
    "2MORO": "Tomorrow",
    "MSG": "Message",
    "TXT": "Text",
    "PIC": "Picture",
    "PPL": "People",
    "THO": "Though",
    "PROB": "Probably",
    "DEETS": "Details",
    "K": "Okay",
    "KK": "Okay Okay",
    "W8": "Wait",
    "GR8": "Great",
    "LMAO": "Laughing My Ass Off",
    "ROFL": "Rolling On The Floor Laughing",
    "IYKYK": "If You Know You Know",
    "FR": "For Real",
    "NGL": "Not Gonna Lie",
    "ISTG": "I Swear To God",
    "RN": "Right Now",
    "AFK": "Away From Keyboard",
    "GGWP": "Good Game Well Played",
    "ICY": "I See You"
}

print(len(short_forms))

101

In [ ]:
def chat_convertion(text):
  new_text = []
  for w in text.split():
    if w.upper() in short_forms:
      new_text.append(short_forms[w.upper()])
    else:
      new_text.append(w)
  return " ".join(new_text)

In [ ]:
chat_convertion('GN buddy')

'Good Night buddy'